name: popup_menu_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.3.10"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  popup_menu:
    path: ../


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/copy.png
