name: popup_menu
description: A Flutter popup menu.Writted with pure dart, supported both iOS and Android.
version: 1.0.5
homepage: https://github.com/chinabrant/popup_menu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

